const $=s=>document.querySelector(s);let session=JSON.parse(localStorage.getItem('macrorelay-session')||'null'),state=null,lastEvent=0,timer;
const toast=m=>{const e=$('#toast');e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)};
async function api(path,options={}){const headers={'Content-Type':'application/json',...(options.headers||{})};if(session?.token)headers.Authorization=`Bearer ${session.token}`;const r=await fetch(path,{...options,headers});const data=await r.json().catch(()=>({ok:false,error:'invalid_response'}));if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);return data}
function connected(yes){$('#connection').textContent=yes?'온라인':'오프라인';$('#connection').className=`status ${yes?'online':'offline'}`}
function showDashboard(){const yes=!!session;$('#pair-card').hidden=yes;$('#dashboard').hidden=!yes;if(yes){$('#device-name').textContent=session.device_name||'MacroRelay PC';refresh()}}
$('#pair-form').addEventListener('submit',async e=>{e.preventDefault();const code=$('#pair-code').value.replace(/\D/g,'');$('#pair-error').textContent='';try{const r=await api('/api/pair',{method:'POST',body:JSON.stringify({code})});session={device_id:r.device_id,device_name:r.device_name,token:r.token};localStorage.setItem('macrorelay-session',JSON.stringify(session));showDashboard();toast('PC와 연결되었습니다')}catch(err){$('#pair-error').textContent='코드가 올바르지 않거나 만료되었습니다.'}});
function renderMacros(items=[]){const q=$('#macro-search').value.trim().toLocaleLowerCase();const rows=items.filter(x=>`${x.name} ${x.description}`.toLocaleLowerCase().includes(q));$('#macro-count').textContent=`${items.length}개`;$('#macro-list').innerHTML=rows.length?rows.map(x=>`<article class="macro"><div><h3>${escapeHtml(x.name)}</h3><p>${escapeHtml(x.description||`${x.steps}단계`)}</p></div><button class="run-btn" data-name="${escapeAttr(x.name)}" ${state?.running?'disabled':''} aria-label="실행">▶</button></article>`).join(''):'<p class="empty">검색 결과가 없습니다.</p>'}
function renderDevice(device){connected(device.online);state=device.state||{};$('#device-name').textContent=device.name||session.device_name;$('#run-state').textContent=state.running?'실행 중':device.online?'대기 중':'연결 끊김';$('#progress').textContent=state.progress_step?`${state.progress_step}단계`:'—';$('#running-name').textContent=state.running_macro||'실행 중인 매크로 없음';$('.pulse').classList.toggle('active',!!state.running);$('#stop').disabled=!state.running||!state.capabilities?.stop;renderMacros(state.macros||[])}
function escapeHtml(s){const d=document.createElement('div');d.textContent=String(s);return d.innerHTML}function escapeAttr(s){return escapeHtml(s).replace(/"/g,'&quot;')}
async function command(action,payload={}){return api(`/api/devices/${encodeURIComponent(session.device_id)}/commands`,{method:'POST',body:JSON.stringify({action,payload})})}
async function refresh(){if(!session)return;try{const [d,e]=await Promise.all([api(`/api/devices/${encodeURIComponent(session.device_id)}`),api(`/api/devices/${encodeURIComponent(session.device_id)}/events?after=${lastEvent}`)]);renderDevice(d.device);renderEvents(e.events||[]);if(!state?.running)command('status').catch(()=>{})}catch(err){connected(false);if(err.message==='app_unauthorized'){disconnect()} }clearTimeout(timer);timer=setTimeout(refresh,3000)}
function renderEvents(items){if(!items.length)return;lastEvent=Math.max(lastEvent,...items.map(x=>x.id));const box=$('#events');const old=box.querySelector('.empty');if(old)old.remove();items.sort((a,b)=>b.id-a.id).forEach(x=>{const row=document.createElement('div');row.className='event';const when=new Date(x.created*1000).toLocaleString('ko-KR',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'});row.innerHTML=`<strong>${escapeHtml(x.message)}</strong><span>${escapeHtml(when)}</span>`;box.prepend(row);if(document.hidden&&'Notification'in window&&Notification.permission==='granted')new Notification('MacroRelay',{body:x.message})})}
$('#macro-list').addEventListener('click',async e=>{const b=e.target.closest('[data-name]');if(!b)return;if(!confirm(`‘${b.dataset.name}’ 매크로를 실행할까요?`))return;try{await command('run_macro',{name:b.dataset.name});toast('실행 명령을 보냈습니다');setTimeout(refresh,500)}catch(err){toast(`실행 실패: ${err.message}`)}});
$('#stop').addEventListener('click',async()=>{if(!confirm('실행 중인 매크로를 정지할까요?'))return;await command('stop_macro');toast('정지 명령을 보냈습니다');setTimeout(refresh,500)});$('#refresh').onclick=refresh;$('#macro-search').addEventListener('input',()=>renderMacros(state?.macros||[]));
function disconnect(){clearTimeout(timer);localStorage.removeItem('macrorelay-session');session=null;state=null;connected(false);showDashboard()}$('#disconnect').onclick=()=>{if(confirm('이 PC 연결을 해제할까요?'))disconnect()};
if('serviceWorker'in navigator)navigator.serviceWorker.register('/service-worker.js').catch(()=>{});if('Notification'in window&&Notification.permission==='default')document.addEventListener('click',()=>Notification.requestPermission(),{once:true});showDashboard();
