const $=s=>document.querySelector(s);let session=JSON.parse(localStorage.getItem('macrorelay-session')||'null'),state=null,lastEvent=0,timer,initialEventsDone=false,refreshInFlight=false;
function playChime(){try{const AudioCtx=window.AudioContext||window.webkitAudioContext;if(!AudioCtx)return;const ctx=new AudioCtx();const now=ctx.currentTime;const osc=ctx.createOscillator();const gain=ctx.createGain();osc.type='sine';osc.frequency.setValueAtTime(880,now);osc.frequency.exponentialRampToValueAtTime(1318.5,now+0.12);gain.gain.setValueAtTime(0.3,now);gain.gain.exponentialRampToValueAtTime(0.01,now+0.35);osc.connect(gain);gain.connect(ctx.destination);osc.start(now);osc.stop(now+0.35)}catch(_){}}
const toast=(m,duration=3200)=>{const e=$('#toast');if(!e)return;e.textContent=m;e.classList.add('show');clearTimeout(e._timer);e._timer=setTimeout(()=>e.classList.remove('show'),duration)};
function triggerNotification(title,message){playChime();if(navigator.vibrate){try{navigator.vibrate([200,100,200])}catch(_){}}toast(`🔔 [${title||'알림'}] ${message}`,4000);if('Notification'in window&&Notification.permission==='granted'){try{new Notification(title||'MacroRelay',{body:message,icon:'/icon.svg',badge:'/icon.svg',tag:'macrorelay-event-'+Date.now()})}catch(_){}}}
function updateNotificationPermissionUI(){const permCard=$('#notify-perm-card');if(!permCard)return;permCard.hidden=!('Notification'in window&&Notification.permission!=='granted'&&Notification.permission!=='denied')}
async function api(path,options={}){const headers={'Content-Type':'application/json',...(options.headers||{})};if(session?.token)headers.Authorization=`Bearer ${session.token}`;const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),10000);try{const r=await fetch(path,{...options,headers,signal:options.signal||controller.signal});const data=await r.json().catch(()=>({ok:false,error:'invalid_response'}));if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);return data}finally{clearTimeout(timeout)}}
function connected(yes){$('#connection').textContent=yes?'온라인':'오프라인';$('#connection').className=`status ${yes?'online':'offline'}`}
function showDashboard(){const yes=!!session;$('#pair-card').hidden=yes;$('#dashboard').hidden=!yes;if(yes){$('#device-name').textContent=session.device_name||'MacroRelay PC';refresh()}}
$('#pair-form').addEventListener('submit',async e=>{e.preventDefault();const code=$('#pair-code').value.replace(/\D/g,'');$('#pair-error').textContent='';try{const r=await api('/api/pair',{method:'POST',body:JSON.stringify({code})});session={device_id:r.device_id,device_name:r.device_name,token:r.token};localStorage.setItem('macrorelay-session',JSON.stringify(session));showDashboard();toast('PC와 연결되었습니다')}catch(err){$('#pair-error').textContent='코드가 올바르지 않거나 만료되었습니다.'}});
function renderMacros(items=[]){const q=$('#macro-search').value.trim().toLocaleLowerCase();const rows=items.filter(x=>`${x.name} ${x.description}`.toLocaleLowerCase().includes(q));$('#macro-count').textContent=`${items.length}개`;const canRun=!!state?.online&&!state?.running&&state?.capabilities?.run!==false;$('#macro-list').innerHTML=rows.length?rows.map(x=>`<article class="macro"><div><h3>${escapeHtml(x.name)}</h3><p>${escapeHtml(x.description||`${x.steps}단계`)}</p></div><button class="run-btn" data-name="${escapeAttr(x.name)}" ${canRun?'':'disabled'} title="${canRun?'실행':'PC 연결 또는 원격 실행 권한이 필요합니다'}" aria-label="실행">▶</button></article>`).join(''):'<p class="empty">검색 결과가 없습니다.</p>'}
function renderDevice(device){connected(device.online);state={...(device.state||{}),online:!!device.online};$('#device-name').textContent=device.name||session.device_name;$('#run-state').textContent=state.running?'실행 중':device.online?'대기 중':'연결 끊김';$('#progress').textContent=state.progress_step?`${state.progress_step}단계`:'—';$('#running-name').textContent=state.running_macro||'실행 중인 매크로 없음';$('.pulse').classList.toggle('active',!!state.running);$('#stop').disabled=!state.running||state.capabilities?.stop===false;renderMacros(state.macros||[])}
function escapeHtml(s){const d=document.createElement('div');d.textContent=String(s);return d.innerHTML}function escapeAttr(s){return escapeHtml(s).replace(/"/g,'&quot;')}
async function command(action,payload={}){return api(`/api/devices/${encodeURIComponent(session.device_id)}/commands`,{method:'POST',body:JSON.stringify({action,payload})})}
async function refresh(){if(!session||refreshInFlight)return;refreshInFlight=true;try{const [d,e]=await Promise.all([api(`/api/devices/${encodeURIComponent(session.device_id)}`),api(`/api/devices/${encodeURIComponent(session.device_id)}/events?after=${lastEvent}`)]);renderDevice(d.device);renderEvents(e.events||[])}catch(err){connected(false);if(state)state={...state,online:false};renderMacros(state?.macros||[]);if(err.message==='app_unauthorized'){disconnect()}else if(err.name==='AbortError'){toast('중계 서버 응답 시간이 초과되었습니다.')} }finally{refreshInFlight=false;clearTimeout(timer);timer=setTimeout(refresh,3000)}}
function renderEvents(items){if(!items.length){initialEventsDone=true;return}const isFirstLoad=!initialEventsDone&&lastEvent===0;lastEvent=Math.max(lastEvent,...items.map(x=>x.id));const box=$('#events');const old=box.querySelector('.empty');if(old)old.remove();items.sort((a,b)=>b.id-a.id).forEach(x=>{const row=document.createElement('div');row.className='event';const when=new Date(x.created*1000).toLocaleString('ko-KR',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'});const title=x.payload?.title||'';row.innerHTML=`<strong>${title?`[${escapeHtml(title)}] `:''}${escapeHtml(x.message)}</strong><span>${escapeHtml(when)}</span>`;box.prepend(row);if(!isFirstLoad){triggerNotification(title||'MacroRelay',x.message)}});initialEventsDone=true}
$('#macro-list').addEventListener('click',async e=>{const b=e.target.closest('[data-name]');if(!b||b.disabled)return;if(!confirm(`‘${b.dataset.name}’ 매크로를 실행할까요?`))return;b.disabled=true;try{await command('run_macro',{name:b.dataset.name});toast('실행 명령을 보냈습니다');setTimeout(refresh,500)}catch(err){toast(`실행 실패: ${err.message}`);renderMacros(state?.macros||[])}});
$('#stop').addEventListener('click',async()=>{if(!confirm('실행 중인 매크로를 정지할까요?'))return;await command('stop_macro');toast('정지 명령을 보냈습니다');setTimeout(refresh,500)});$('#refresh').onclick=refresh;$('#macro-search').addEventListener('input',()=>renderMacros(state?.macros||[]));
function disconnect(){clearTimeout(timer);localStorage.removeItem('macrorelay-session');session=null;state=null;connected(false);showDashboard()}$('#disconnect').onclick=()=>{if(confirm('이 PC 연결을 해제할까요?'))disconnect()};
const permBtn=$('#notify-perm-btn');if(permBtn){permBtn.onclick=async()=>{if('Notification'in window){const perm=await Notification.requestPermission();updateNotificationPermissionUI();if(perm==='granted'){playChime();toast('🔔 스마트폰 알림이 켜졌습니다!')}else{toast('알림 권한이 허용되지 않았습니다.')}}}}
if('serviceWorker'in navigator)navigator.serviceWorker.register('/service-worker.js').catch(()=>{});if('Notification'in window&&Notification.permission==='default'){document.addEventListener('click',()=>{Notification.requestPermission().then(updateNotificationPermissionUI).catch(()=>{})},{once:true})}updateNotificationPermissionUI();showDashboard();
