from __future__ import annotations


# 이전 Studio의 '기능별 단축키' 개념을 현재 화면과 액션에 맞게 복구한 목록입니다.
# 기본값이 빈 항목도 설정에서 사용자가 임의로 배정할 수 있습니다.
STUDIO_SHORTCUT_SPECS = [
    ("tab_macro", "화면 이동 · 매크로 빌더", "F5"),
    ("tab_image", "화면 이동 · 이미지 편집", "F6"),
    ("tab_browser", "화면 이동 · 브라우저 액션 준비", "F7"),
    ("tab_hotkey", "화면 이동 · Quick Slots", "F8"),
    ("tab_export", "화면 이동 · 내보내기", ""),
    ("tab_hotkey_settings", "화면 이동 · 기능 단축키 설정", ""),
    ("tab_data", "화면 이동 · 데이터 테이블", ""),
    ("action_create_macro", "빌더 · 새 매크로", "Shift+F2"),
    ("action_add_node", "빌더 · 선택 액션 노드 추가", "Ctrl+Return"),
    ("action_save_step", "빌더 · 현재 노드 저장", "Ctrl+S"),
    ("action_run_macro", "빌더 · 현재 매크로 실행", "Ctrl+R"),
    ("action_duplicate_node", "빌더 · 현재 노드 복제", "Ctrl+D"),
    ("action_fit_nodes", "빌더 · 전체 노드 보기", "Ctrl+0"),
    ("action_capture_cursor", "빌더 · 마우스 좌표 선택(클릭/F4 저장)", "Ctrl+Shift+C"),
    ("action_open_step_editor", "빌더 · 액션 상세 설정 열기", "Ctrl+E"),
    ("action_refresh_macros", "빌더 · 매크로 새로고침", ""),
    ("action_smart_record", "자동화 · 스마트 동작 녹화 시작", "F9"),
    ("action_quick_automation", "자동화 · 빠른 액션 설정", "Ctrl+Shift+A"),
    ("action_diagnose_automation", "자동화 · 현재 매크로 진단", "Ctrl+Shift+D"),
    ("action_test_selected_step", "자동화 · 선택 단계만 테스트", "Ctrl+Shift+T"),
    ("helper_typing", "노드 준비 · 텍스트 입력", "Ctrl+F1"),
    ("helper_delay", "노드 준비 · 대기", "Ctrl+F2"),
    ("helper_coord", "노드 준비 · 좌표 기준", ""),
    ("helper_inactive", "노드 준비 · 비활성 클릭", ""),
    ("helper_image", "노드 준비 · 이미지 서치", ""),
    ("helper_dom", "노드 준비 · 브라우저 요소", ""),
    ("helper_ocr", "노드 준비 · OCR", ""),
    ("helper_table", "노드 준비 · 데이터 테이블", ""),
    ("helper_flow", "노드 준비 · 반복 이동", ""),
    ("helper_submacro", "노드 준비 · 서브매크로", ""),
    ("helper_text_condition", "노드 준비 · 텍스트 조건", ""),
    ("action_add_asset", "이미지 · 파일 추가", ""),
    ("action_capture_asset", "이미지 · 화면 범위 캡처", "Ctrl+Shift+I"),
    ("action_edit_asset", "이미지 · 선택 항목 편집", ""),
    ("action_refresh_assets", "이미지 · 폴더 동기화", ""),
    ("action_open_table_dialog", "데이터 · 테이블 열기", ""),
    ("action_refresh_tables", "데이터 · 새로고침", ""),
    ("action_delete_current", "공통 · 현재 선택 항목 보관", ""),
    ("action_export", "내보내기 · AHK/EXE 생성", ""),
    ("action_preview", "내보내기 · 스크립트 미리보기", ""),
    ("action_test_run", "내보내기 · 테스트 실행", ""),
]
